name: friend_builder
description: "Make friendships stronger"
publish_to: 'none'
version: 2.0.3

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  flutter_local_notifications: ^17.1.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_typeahead: ^5.2.0
  intl: ^0.19.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  sqflite: ^2.3.3+1
  timezone: ^0.9.3
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - logo/splash.png

